llm_model_name: "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo"
base_dir: "/Users/wojtek/Documents/bioinf/coordinates-lit/"
paths:
  coordinates_extraction_examples: "data/coordinates-extraction/example-coordinates.txt"
  coordinates_regexes: "data/coordinates-extraction/coordinates_regexes.json"
  so_obo: 'data/sequence-ontology/so-edit.obo'
  lancedb_path: 'index/lancedb'

# API keys and credentials
api:
  together_api_key: "tgp_v1_lKW5Q0Txf28ByQg_Ys06noFmMYO8G_sKHd1eqUexC7s"
  openai_api_key: ""  # Add your OpenAI API key here

# Contact information for API services
contact:
  email: "sitekwb@gmail.com"  # Email for PubTator API