# Domyślna konfiguracja aplikacji

llm:
  provider: "together"
  model_name: "meta-llama/Meta-Llama-3.1-8B-Instruct"

# Default models for different tasks
models:
  embeddings:
    default: "sentence-transformers/all-MiniLM-L6-v2"
    alternatives:
      - "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
      - "NeuML/pubmedbert-base-embeddings"
  tokenizer:
    default: "bert-base-uncased"
  classification:
    sentiment: "cardiffnlp/twitter-roberta-base-sentiment-latest"
    default: "cardiffnlp/twitter-roberta-base-sentiment-latest"
  chat:
    default: "meta-llama/Meta-Llama-3.1-8B-Instruct"
    provider: "together"

base_dir: "./"
paths:
  coordinates_extraction_examples: "data/coordinates-extraction/example-coordinates.txt"
  coordinates_regexes: "data/coordinates-extraction/coordinates_regexes.json"
  so_obo: 'data/sequence-ontology/so-edit.obo'
  lancedb_path: 'index/lancedb'

# API keys and credentials
api:
  together_api_key: "tgp_v1_lKW5Q0Txf28ByQg_Ys06noFmMYO8G_sKHd1eqUexC7s"
  openai_api_key: ""  # Add your OpenAI API key here

# Contact information for API services
contact:
  email: "sitekwb@gmail.com"  # Email for PubTator API