# Konfiguracja środowiska deweloperskiego

# Ustawienia API
api:
  timeout: 30
  retry_attempts: 3
  retry_delay: 1

# Ustawienia logowania
logging:
  level: DEBUG
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/development.log"

# Ustawienia cache
cache:
  enabled: true
  expiry: 3600  # 1 godzina
  directory: "data/cache"

# Ustawienia danych
data:
  raw_directory: "data/raw"
  processed_directory: "data/processed"
  max_file_size: 10485760  # 10MB

# Ustawienia analizy
analysis:
  batch_size: 100
  max_retries: 3
  timeout: 300  # 5 minut 