# Konfiguracja środowiska produkcyjnego

llm:
  provider: "together"
  model_name: "meta-llama/Meta-Llama-3.1-8B-Instruct"

# Default models for different tasks
models:
  embeddings:
    default: "sentence-transformers/all-MiniLM-L6-v2"
    alternatives:
      - "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
      - "NeuML/pubmedbert-base-embeddings"
  tokenizer:
    default: "bert-base-uncased"
  classification:
    sentiment: "cardiffnlp/twitter-roberta-base-sentiment-latest"
    default: "cardiffnlp/twitter-roberta-base-sentiment-latest"
  chat:
    default: "meta-llama/Meta-Llama-3.1-8B-Instruct"
    provider: "together"

base_dir: "/data/coordinates-lit/"

# Ustawienia API
api:
  timeout: 60
  retry_attempts: 5
  retry_delay: 2

# Ustawienia logowania
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "/var/log/coordinates-lit/production.log"

# Ustawienia cache
cache:
  enabled: true
  expiry: 86400  # 24 godziny
  directory: "/var/cache/coordinates-lit"

# Ustawienia danych
data:
  raw_directory: "/var/data/coordinates-lit/raw"
  processed_directory: "/var/data/coordinates-lit/processed"
  max_file_size: 104857600  # 100MB

# Ustawienia analizy
analysis:
  batch_size: 1000
  max_retries: 5
  timeout: 1800  # 30 minut 