# Konfiguracja środowiska testowego

llm:
  provider: "together"
  model_name: "meta-llama/Meta-Llama-3.1-8B-Instruct"

# Default models for different tasks
models:
  embeddings:
    default: "sentence-transformers/all-MiniLM-L6-v2"
    alternatives:
      - "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
      - "NeuML/pubmedbert-base-embeddings"
  tokenizer:
    default: "bert-base-uncased"
  classification:
    sentiment: "cardiffnlp/twitter-roberta-base-sentiment-latest"
    default: "cardiffnlp/twitter-roberta-base-sentiment-latest"
  chat:
    default: "meta-llama/Meta-Llama-3.1-8B-Instruct"
    provider: "together"

base_dir: "/tmp/coordinates-lit-test/"

# Ustawienia API
api:
  timeout: 5
  retry_attempts: 1
  retry_delay: 0

# Ustawienia logowania
logging:
  level: WARNING
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/test.log"

# Ustawienia cache
cache:
  enabled: false
  expiry: 60  # 1 minuta
  directory: "tests/fixtures/cache"

# Ustawienia danych
data:
  raw_directory: "tests/fixtures/raw"
  processed_directory: "tests/fixtures/processed"
  max_file_size: 1048576  # 1MB

# Ustawienia analizy
analysis:
  batch_size: 10
  max_retries: 1
  timeout: 30  # 30 sekund 